Connector profitbase
adventum/airbyte pull request #16
Opened 2024-08-29 08:42 UTC by Mercys-s

Есть 3 схемы и стрима: house, projects, properties. В Схемах уже прописаны поля которые нужны (Допустим их по 20 в каждом)

Аутентификацию я буду проходить с помощью ProfitbaseAuthenticator. Так как чтобы получить доступ к API, нужно сначала получить токен, с помощью api_key. Поэтому перед работой со стримами я буду получать токен, и передавать его уже к запросам на выгрузку данных
То есть я не буду передавать его как объект, как в некоторых коннекторах, а буду разово использовать его метод, на получение access_token'a

Идея заключается в прохождении в цикле по каждому стриму: я буду делать запрос к api, например для house, будет возвращаться множество объектов, в каждом из которых по 100 полей.
Я буду парсить эти 100 полей, и забирать оттуда 20, в соответствии со схемой, и записывать их в AirbyteMessage

Так я буду проходить по всем 3 стримам, и по итогу это все должно пойти в БД

Я в правильную сторону иду?

2024-08-29 09:54 UTC, stamplevskiyd requested changes

2024-08-29 09:54 UTC, stamplevskiyd commented on airbyte-integrations/connectors/source-profitbase/setup.py
> +    "airbyte-cdk~=0.2",
Обнови до последнего, не будем использовать древние версии

2024-08-29 09:54 UTC, stamplevskiyd commented on airbyte-integrations/connectors/source-profitbase/source_profitbase/auth.py
> +    def get_access_token(api_key, account_number):
Тайпингов нет, а так auth.py вроде бы выглядит прилично

2024-08-29 09:54 UTC, stamplevskiyd commented on airbyte-integrations/connectors/source-profitbase/source_profitbase/source.py
> +class SourceProfitbase(Source):
Зачем это? Выглядит, будто тут нет кастомной логики и ты просто дублируешь код

2024-08-29 09:54 UTC, stamplevskiyd commented on airbyte-integrations/connectors/source-profitbase/source_profitbase/streams.py
> +        headers = {
AirByte может сам сделать такой запрос. Это будет работать, но это лишнее. Глянь, например, source-cian

2024-09-02 12:25 UTC, Mercys-s commented on airbyte-integrations/connectors/source-profitbase/setup.py
> +    "airbyte-cdk~=0.2",
До последнего, это до 4.2?
Я на всякий случай пока 0.2 оставлю, если в будущем будет конфликтов, тогда поменяю, хорошо?

2024-09-02 12:26 UTC, merged